DROP DATABASE IF EXISTS sign;
CREATE DATABASE sign;
USE sign;
CREATE TABLE login(
id INT(15) PRIMARY KEY,
firstname VARCHAR(30) NOT NULL,
lastname VARCHAR(30) NOT NULL,
username VARCHAR(30)  UNIQUE NOT NULL,
password VARCHAR(30) NOT NULL
);